from enum import StrEnum


class SetupState(StrEnum):
    NORMAL = "NORMAL"
    DIP_WATCH = "DIP_WATCH"
    SELLING_EXHAUSTION = "SELLING_EXHAUSTION"
    RIGHT_SIDE_REPAIR = "RIGHT_SIDE_REPAIR"
    CALL_CANDIDATE = "CALL_CANDIDATE"
    BREAKDOWN = "BREAKDOWN"
