"""Options eligibility, analysis, live read-only data, cache, and persistence."""

from app.options.cache import BoundedTTLCache, CacheResult, TTLCache
from app.options.eligibility import evaluate_options_eligibility
from app.options.filters import filter_long_call_contracts
from app.options.models import (
    CandidateStatus,
    ContractFilterStatus,
    DataQualityFlag,
    DeltaRangeStatus,
    EligibilityDecision,
    EligibilityStatus,
    EventDataStatus,
    FilterStageCount,
    MoneynessStatus,
    OptionChainMetadata,
    OptionChainResult,
    OptionCandidateStatus,
    OptionContract,
    OptionFilterResult,
    OptionsAlertPayload,
    OptionsScanResult,
    OptionsScanStatus,
    OptionsScoreBreakdown,
    OptionType,
    ProviderErrorKind,
    ProviderErrorMetadata,
    ProviderResponseMetadata,
    QualifiedOptionAlertPayload,
    ScoredOptionCandidate,
    ScanResultStatus,
)
from app.options.provider import (
    AlpacaOptionsDataProvider,
    MissingOptionsCredentialsError,
    OptionsAuthenticationError,
    OptionsAuthorizationError,
    OptionsDataProvider,
    OptionsEntitlementError,
    OptionsInvalidResponseError,
    OptionsNetworkError,
    OptionsPaginationError,
    OptionsProviderError,
    OptionsRateLimitError,
    OptionsServerError,
)
from app.options.ranking import rank_candidates, rank_option_candidates
from app.options.repository import OptionsRepository, OptionsScanRepository
from app.options.scoring import score_option_candidate, score_option_contract
from app.options.service import OptionsScanService, QualifiedScanError

__all__ = [
    "AlpacaOptionsDataProvider",
    "BoundedTTLCache",
    "CacheResult",
    "CandidateStatus",
    "ContractFilterStatus",
    "DataQualityFlag",
    "DeltaRangeStatus",
    "EligibilityDecision",
    "EligibilityStatus",
    "EventDataStatus",
    "FilterStageCount",
    "MoneynessStatus",
    "MissingOptionsCredentialsError",
    "OptionChainMetadata",
    "OptionChainResult",
    "OptionCandidateStatus",
    "OptionContract",
    "OptionFilterResult",
    "OptionsAlertPayload",
    "OptionsScanResult",
    "OptionsScanStatus",
    "OptionsScoreBreakdown",
    "OptionType",
    "OptionsAuthenticationError",
    "OptionsAuthorizationError",
    "OptionsDataProvider",
    "OptionsEntitlementError",
    "OptionsInvalidResponseError",
    "OptionsNetworkError",
    "OptionsPaginationError",
    "OptionsProviderError",
    "OptionsRateLimitError",
    "OptionsRepository",
    "OptionsScanRepository",
    "OptionsScanService",
    "QualifiedScanError",
    "OptionsServerError",
    "ProviderErrorKind",
    "ProviderErrorMetadata",
    "ProviderResponseMetadata",
    "QualifiedOptionAlertPayload",
    "ScoredOptionCandidate",
    "ScanResultStatus",
    "TTLCache",
    "evaluate_options_eligibility",
    "filter_long_call_contracts",
    "rank_candidates",
    "rank_option_candidates",
    "score_option_candidate",
    "score_option_contract",
]
